### ISSUE TITLE
How to set such a rule?

### ISSUE THREAD

**Issue by DaPoHou** [Vavooon/SIMSelector#1]
First of all, thank you very much for your efforts. This is great.
Now I found some problems during use. For example, I just want to call a 5-digit phone number that starts with 6, for example, 698814 I set the rules like this:
6#####
It can call from desired SIM to the number 698814 .
But,the number 240 698814 45 was also called from the SIM. 
How to solve? Thank you

**Comment by Vavooon** [comment]
Hello.
Since the application uses regular expressions you may try to use **^** character to select only numbers starting with 6, so entire pattern would look like `^6#####`.
It also works for **$**, meaning end of a number.

**Comment by DaPoHou** [comment]
Thank you very much.
This application uses regular expressions and it's pretty cool. Now it works very well. Thank you again very much.
